variables:
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.13' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path

steps:
- script: |
    go version
    go run src/main.go
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'